package com.java1234.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-22T16:30:07.626+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.java1234.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoleByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.java1234.webservice.Role> getRoleByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.java1234.webservice.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRolesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.java1234.webservice.MyRoleArray getRoles();
}
